### ISSUE TITLE
Add color picker

### ISSUE THREAD

**Issue by severdia** [severdia/chromacolors#1]
Need to research color pickers for the color field. Some options:

https://jscolor.com

https://iro.js.org

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color

https://www.cssscript.com/demo/color-picker-coloris/

https://github.com/R-TEK/colr_pickr/

https://github.com/Simonwep/pickr

**Comment by twhiteheadzm** [comment]
Added the native html one. let me know if you prefer another.

**Comment by severdia** [comment]
This is fine for this first version.
