### ISSUE TITLE
Add "constrain" setting

### ISSUE THREAD

**Issue by severdia** [severdia/chromacolors#5]
When there are enough steps, and based on the Position setting, the colors eventually end up as black, white or both. The steps are a fixed distance from one another so that means there could be many white and many black colors at the start or end. To avoid this, there should be a "constrain" setting that limits the start to one white color and the end to one black color, and adjusts the distance according to the number of steps. If the user choose the "Start" position, this would only affect the end color and vice-versa if they choose the "End" position.

This would just be a checkbox to the right of the Steps dropdown called "Constrain" (and be unchecked by default) that would constrain the color scheme to 1 black/white color at the beginning/end of the scheme.

**Comment by twhiteheadzm** [comment]
I have added the feature and I believe it does what you want. I wasn't sure of the best formula to get the steps using **darken**, so I used the **scale** feature from the library you are using.

**Comment by severdia** [comment]
Yes, that seems to work, but the checkbox is broken.

![Screen Shot 2021-12-10 at 3 14 20 PM](https://user-images.githubusercontent.com/355924/145652736-69ebdc07-e097-4b97-98f2-8d2e012fe310.png)

**Comment by twhiteheadzm** [comment]
It was a difference between chrome and safari. I have fixed it.
